[package]
name = "hexrails"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sudo apt install g++ pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
bevy = { version = "0.7", features = ["dynamic"] }
bevy-inspector-egui = "0.11.0"
petgraph = "0.6.2"
bevy_prototype_debug_lines = "0.7.1"

